version: '3.8'

networks:
  monitoring:
    driver: bridge

services:
  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - 3000:3000
    user: '472'
    volumes:
      - ./grafana-storage:/var/lib/grafana
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    expose:
      - 9090
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - monitoring